### ISSUE TITLE
colored header and expression

### ISSUE THREAD

**Issue by msagarpatel** [benknoble/tag-tracks#4]
Is there a way to color the header, and expressions like `:tags` does?

<img width="515" alt="Screen Shot 2022-03-03 at 2 22 32 AM" src="https://user-images.githubusercontent.com/42593885/156516379-d98b0e87-b497-4aa0-97b2-f339b8e0cdef.png">

**Comment by benknoble** [comment]
Yes, this should be straightforward.

Try something like
```vim
  syntax match Title /\vItem\s+Tag\s+Match\s+Origin/
```
around https://github.com/benknoble/tag-tracks/blob/67c3fc96f6c2f74cffec55754cb0298d0b2873c2/autoload/tagtracks.vim#L87
