### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by Konfekt** [benknoble/tag-tracks#6]
Great, just today I wondered if there's not any plug-in that displays the tagstack nicely as one gets lost in other people's code. And indeed now there is. It took an astonishingly long while. Maybe https://github.com/wellle/context.vim is a good companion.

If ever you know of a plug-in that displays the corresponding tag stack hierarchy (instead of the file tree), I'd be happy to know.

**Comment by benknoble** [comment]
Glad you like it! I'm pretty sure I whipped this up explicitly from @msagarpatel's idea, but I don't remember now. Glad to know it will help others, though.
